apiVersion: v1
kind: Service
metadata:
  name: sync-service
  namespace: sync-service
  labels:
    app: sync-service
spec:
  type: ClusterIP
  selector:
    app: sync-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
